# version: '2.2'

# services:
#   asmpmenteebackend:
#     restart: unless-stopped
#     build:
#       context: ./Backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     entrypoint: /Backend/wsgi-entrypoint.sh
#     volumes:
#       - ./Backend:/Backend/
#     expose:
#       - 8000
#     networks:
#       - mynetwork
  

#   asmpmenteefrontend:
#     build:
#       context: ./asmp
#       dockerfile: Dockerfile
#     ports:
#       - "5002:5002"
#     volumes:
#       - ./asmp:/asmp
#     networks:
#       - mynetwork

# networks:
#   mynetwork:
#     name: yearbook23_mynetwork



version: '2.2'

services:
  asmpmenteebackend:
    restart: unless-stopped
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    entrypoint: /Backend/wsgi-entrypoint.sh
    volumes:
      - ./Backend:/Backend/
    expose:
      - 8000
    networks:
      - mynetwork
  

  asmpmenteefrontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    volumes:
      - ./Frontend:/Frontend
    networks:
      - mynetwork

networks:
  mynetwork:
    name: yearbook23_mynetwork