HOSTEL_CHOICES = [
    ('hostel_1', 'Hostel 1'),
    ('hostel_2', 'Hostel 2'),
    ('hostel_3', 'Hostel 3'),
    ('hostel_4', 'Hostel 4'),
    ('hostel_5', 'Hostel 5'),
    ('hostel_6', 'Hostel 6'),
    ('hostel_7', 'Hostel 7'),
    ('hostel_8', 'Hostel 8'),
    ('hostel_9', 'Hostel 9'),
    ('hostel_10', 'Hostel 10'),
    ('hostel_11', 'Hostel 11'),
    ('hostel_12', 'Hostel 12'),
    ('hostel_13', 'Hostel 13'),
    ('hostel_14', 'Hostel 14'),
    ('hostel_15', 'Hostel 15'),
    ('tansa', 'Tansa'),
    ('qip', 'QIP'),
]

YEAR_CHOICES = [
    ('2023', '2023'),
    ('2022', '2022'),
    ('2021', '2021'),
    ('2020', '2020'),
    ('2019', '2019'),
    ('2018', '2018'),
    ('2017', '2017'),
    ('2016', '2016'),
    ('2015', '2015'),
    ('2014', '2014'),
    ('2013', '2013'),
    ('2012', '2012'),
    ('2011', '2011'),
    ('2010', '2010'),
    ('2009', '2009'),
    ('2008', '2008'),
    ('2007', '2007'),
    ('2006', '2006'),
    ('2005', '2005'),
    ('2004', '2004'),
    ('2003', '2003'),
    ('2002', '2002'),
    ('2001', '2001'),
    ('2000', '2000'),
    ('1999', '1999'),
    ('1998', '1998'),
    ('1997', '1997'),
    ('1996', '1996'),
    ('1995', '1995'),
    ('1994', '1994'),
    ('1993', '1993'),
    ('1992', '1992'),
    ('1991', '1991'),
    ('1990', '1990'),
    ('1989', '1989'),
    ('1988', '1988'),
    ('1987', '1987'),
    ('1986', '1986'),
    ('1985', '1985'),
    ('1984', '1984'),
    ('1983', '1983'),
    ('1982', '1982'),
    ('1981', '1981'),
    ('1980', '1980'),
    ('1979', '1979'),
    ('1978', '1978'),
    ('1977', '1977'),
    ('1976', '1976'),
    ('1975', '1975'),
    ('1974', '1974'),
    ('1973', '1973'),
    ('1972', '1972'),
    ('1971', '1971'),
    ('1970', '1970'),
    ('1969', '1969'),
    ('1968', '1968'),
    ('1967', '1967'),
    ('1966', '1966'),
    ('1965', '1965'),
    ('1964', '1964'),
    ('1963', '1963'),
    ('1962', '1962'),
]

DEGREE_CHOICES = [
    ('btech', 'B.Tech'),
    ('bs', 'B.S'),
    ('dual_degree', 'Dual Degree'),
    ('mtech', 'M.Tech'),
    ('msc', 'M.Sc'),
    ('phd', 'PhD'),
    ('other_degree', 'Other Degree'),
]

BRANCH_CHOICES = [
    ('aero', 'Aerospace Engineering'),
    ('cse', 'Computer Science Engineering'),
    ('ee', 'Electrical Engineering'),
    ('mech', 'Mechanical Engineering'),
    ('chem', 'Chemistry'),
    ('biosci', 'Biosciences & Bioengineering'),
    ('che', 'Chemical Engineering'),
    ('eco', 'Economics'),
    ('ieor', 'Industrial Engineering and Operations Research'),
    ('metallurgy', 'Metallurgical Engineering and Material Science'),
    ('engphy', 'Engineering Physics'),
    ('envsci', 'Environmental Science & Engineering'),
    ('energy', 'Energy Science & Engineering'),
    ('math', 'Mathematics'),
    ('civil', 'Civil Engineering'),
    ('earthsci', 'Earth Sciences and Resource engineering'),
    ('rural', 'Technology for Rural Areas'),
    ('design', 'Design'),
    ('other', 'Other (If not mentioned above)'),
]

COUNTRY_CHOICES = [
    ('1', 'India'),
    ('2', 'Afghanistan'),
    ('3', 'Albania'),
    ('4', 'Algeria'),
    ('5', 'Andorra'),
    ('6', 'Angola'),
    ('7', 'Antigua and Barbuda'),
    ('8', 'Argentina'),
    ('9', 'Armenia'),
    ('10', 'Australia'),
    ('11', 'Austria'),
    ('12', 'Azerbaijan'),
    ('13', 'The Bahamas'),
    ('14', 'Bahrain'),
    ('15', 'Bangladesh'),
    ('16', 'Barbados'),
    ('17', 'Belarus'),
    ('18', 'Belgium'),
    ('19', 'Belize'),
    ('20', 'Benin'),
    ('21', 'Bhutan'),
    ('22', 'Bolivia'),
    ('23', 'Bosnia and Herzegovina'),
    ('24', 'Botswana'),
    ('25', 'Brazil'),
    ('26', 'Brunei'),
    ('27', 'Bulgaria'),
    ('28', 'Burkina Faso'),
    ('29', 'Burundi'),
    ('30', 'Cabo Verde'),
    ('31', 'Cambodia'),
    ('32', 'Cameroon'),
    ('33', 'Canada'),
    ('34', 'Central African Republic'),
    ('35', 'Chad'),
    ('36', 'Chile'),
    ('37', 'China'),
    ('38', 'Colombia'),
    ('39', 'Comoros'),
    ('40', 'Congo, Democratic Republic of the'),
    ('41', 'Congo, Republic of the'),
    ('42', 'Costa Rica'),
    ('43', 'Côte d’Ivoire'),
    ('44', 'Croatia'),
    ('45', 'Cuba'),
    ('46', 'Cyprus'),
    ('47', 'Czech Republic'),
    ('48', 'Denmark'),
    ('49', 'Djibouti'),
    ('50', 'Dominica'),
    ('51', 'Dominican Republic'),
    ('52', 'East Timor (Timor-Leste)'),
    ('53', 'Ecuador'),
    ('54', 'Egypt'),
    ('55', 'El Salvador'),
    ('56', 'Equatorial Guinea'),
    ('57', 'Eritrea'),
    ('58', 'Estonia'),
    ('59', 'Eswatini'),
    ('60', 'Ethiopia'),
    ('61', 'Fiji'),
    ('62', 'Finland'),
    ('63', 'France'),
    ('64', 'Gabon'),
    ('65', 'The Gambia'),
    ('66', 'Georgia'),
    ('67', 'Germany'),
    ('68', 'Ghana'),
    ('69', 'Greece'),
    ('70', 'Grenada'),
    ('71', 'Guatemala'),
    ('72', 'Guinea'),
    ('73', 'Guinea-Bissau'),
    ('74', 'Guyana'),
    ('75', 'Haiti'),
    ('76', 'Honduras'),
    ('77', 'Hungary'),
    ('78', 'Iceland'),
    ('79', 'Indonesia'),
    ('80', 'Iran'),
    ('81', 'Iraq'),
    ('82', 'Ireland'),
    ('83', 'Israel'),
    ('84', 'Italy'),
    ('85', 'Jamaica'),
    ('86', 'Japan'),
    ('87', 'Jordan'),
    ('88', 'Kazakhstan'),
    ('89', 'Kenya'),
    ('90', 'Kiribati'),
    ('91', 'Korea, North'),
    ('92', 'Korea, South'),
    ('93', 'Kosovo'),
    ('94', 'Kuwait'),
    ('95', 'Kyrgyzstan'),
    ('96', 'Laos'),
    ('97', 'Latvia'),
    ('98', 'Lebanon'),
    ('99', 'Lesoth'),
    ('100', 'Liberia'),
    ('101', 'Libya'),
    ('102', 'Liechtenstein'),
    ('103', 'Lithuania'),
    ('104', 'Luxembourg'),
    ('105', 'Madagascar'),
    ('106', 'Malawi'),
    ('107', 'Malaysia'),
    ('108', 'Maldives'),
    ('109', 'Mali'),
    ('110', 'Malta'),
    ('111', 'Marshall Islands'),
    ('112', 'Mauritania'),
    ('113', 'Mauritius'),
    ('114', 'Mexico'),
    ('115', 'Micronesia'),
    ('116', 'Moldova'),
    ('117', 'Monaco'),
    ('118', 'Mongolia'),
    ('119', 'Montenegro'),
    ('120', 'Morocco'),
    ('121', 'Mozambique'),
    ('122', 'Myanmar (Burma)'),
    ('123', 'Namibia'),
    ('124', 'Nauru'),
    ('125', 'Nepal'),
    ('126', 'Netherlands'),
    ('127', 'New Zealand'),
    ('128', 'Nicaragua'),
    ('129', 'Niger'),
    ('130', 'Nigeria'),
    ('131', 'North Macedonia'),
    ('132', 'Norway'),
    ('133', 'Oman'),
    ('134', 'Pakistan'),
    ('135', 'Palau'),
    ('136', 'Panama'),
    ('137', 'Papua New Guinea'),
    ('138', 'Paraguay'),
    ('139', 'Peru'),
    ('140', 'Philippines'),
    ('141', 'Poland'),
    ('142', 'Portugal'),
    ('143', 'Qatar'),
    ('144', 'Romania'),
    ('145', 'Russia'),
    ('146', 'Rwanda'),
    ('147', 'Saint Kitts and Nevis'),
    ('148', 'Saint Lucia'),
    ('149', 'Saint Vincent and the Grenadines'),
    ('150', 'Samoa'),
    ('151', 'San Marino'),
    ('152', 'Sao Tome and Principe'),
    ('153', 'Saudi Arabia'),
    ('154', 'Senegal'),
    ('155', 'Serbia'),
    ('156', 'Seychelles'),
    ('157', 'Sierra Leone'),
    ('158', 'Singapore'),
    ('159', 'Slovakia'),
    ('160', 'Slovenia'),
    ('161', 'Solomon Islands'),
    ('162', 'Somalia'),
    ('163', 'South Africa'),
    ('164', 'South Sudan'),
    ('165', 'Spain'),
    ('166', 'Sri Lanka'),
    ('167', 'Sudan'),
    ('168', 'Suriname'),
    ('169', 'Sweden'),
    ('170', 'Switzerland'),
    ('171', 'Syria'),
    ('172', 'Taiwan'),
    ('173', 'Tajikistan'),
    ('174', 'Tanzania'),
    ('175', 'Thailand'),
    ('176', 'Togo'),
    ('177', 'Tonga'),
    ('178', 'Trinidad and Tobago'),
    ('179', 'Tunisia'),
    ('180', 'Turkey'),
    ('181', 'Turkmenistan'),
    ('182', 'Tuvalu'),
    ('183', 'Uganda'),
    ('184', 'Ukraine'),
    ('185', 'United Arab Emirates'),
    ('186', 'United Kingdom'),
    ('187', 'United States'),
    ('188', 'Uruguay'),
    ('189', 'Uzbekistan'),
    ('190', 'Vanuatu'),
    ('191', 'Vatican City'),
    ('192', 'Venezuela'),
    ('193', 'Vietnam'),
    ('194', 'Yemen'),
    ('195', 'Zambia'),
    ('196', 'Zimbabwe'),
]

FIELDS  = [
    ('analytics', 'Analytics'),
    ('civil_services', 'Civil Services/Govt. of India'),
    ('core_engineering', 'Core engineering'),
    ('design', 'Design'),
    ('finance', 'Finance'),
    ('it', 'IT'),
    ('management', 'Management'),
    ('management_consulting', 'Management consulting'),
    ('marketing', 'Marketing'),
    ('product_management', 'Product Management'),
    ('research', 'Research'),
    ('strategy_consulting', 'Strategy consulting'),
    ('entrepreneurship', 'Entrepreneurship'),
    ('other', 'Other'),
]

MENTEES = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
]

PREFERENCES = [
    ('no_preference', 'No preference'),
    ('final_year_undergrad', 'Final year undergraduate students'),
    ('other_undergrad', 'Other undergraduate students'),
    ('mtech_students', 'M.Tech students'),
    ('phd_students', 'PhD students'),
]

DEPT_MENTEES_FIELDS = [
    ('No_preference_as_such', 'No preference as such'),
    ('Aerospace_Engineering', 'Aerospace Engineering'),
    ('Biosciences_&Bioengineering', 'Biosciences & Bioengineering'),
    ('Centre_for_Policy_Studies-CPS', 'Centre for Policy Studies - CPS'),
    ('Centre_for_Urban_Science&Engineering-C-USE',
        'Centre for Urban Science & Engineering - C-USE'),
    ('Centre_of_Studies_in_Resources_Engineering-CSRE',
        'Centre of Studies in Resources Engineering - CSRE'),
    ('Chemical_Engineering', 'Chemical Engineering'),
    ('Chemistry', 'Chemistry'),
    ('Civil_Engineering', 'Civil Engineering'),
    ('Climate_Studies', 'Climate Studies'),
    ('Computer_Science&Engineering', 'Computer Science & Engineering'),
    ('Desai_Sethi_Centre_for_Entrepreneurship-DSCE',
        'Desai Sethi Centre for Entrepreneurship - DSCE'),
    ('Earth_Sciences', 'Earth Sciences'),
    ('Educational_Technology', 'Educational Technology'),
    ('Electrical_Engineering', 'Electrical Engineering'),
    ('Energy_Science&Engineering', 'Energy Science & Engineering'),
    ('Humanities&Social_Science', 'Humanities & Social Science'),
    ('IITB-Monash_Research_Academy', 'IITB-Monash Research Academy'),
    ('Industrial_Design_Centre', 'Industrial Design Centre'),
    ('Mathematics', 'Mathematics'),
    ('Mechanical_Engineering', 'Mechanical Engineering'),
    ('Metallurgical_Engineering&_Materials_Science',
        'Metallurgical Engineering & Materials Science'),
    ('Physics', 'Physics'),
    ('Shailesh_J.Mehta_School_of_Management',
        'Shailesh J. Mehta School of Management'),
    ('Systems&_Control_Engineering', 'Systems & Control Engineering'),
    ('CESE', 'CESE'),
    ('Other', 'Other')
]